- Added hasImplementation() method to AttributeManager - Created TestObjective class for finite difference gradient and Hessian checks - Updated Python and NumPy test scripts to do this test. Two problems are persisting:   1) In the NumPy testUnconstrained call to testObjective, the returned value for the      inverse Hessian error is garbage. Testing directly with zakharov.py shows the      correct results.   2) In the Python vector implementation, the test fails because
     .../pyrol/test/python/vector.py", line 54, in dimension
          return self.n
     AttributeError: 'vector' object has no attribute 'n'

     Further investigation suggests it has no self.data member either, which
     is odd since the optimization solver test passes.